<form method="POST" class="bg-light rounded mx-auto p-3" style="width: 640px;">
    <?php if(isset($this->user)): ?>
        <div class="mb-4">
            <label class="form-label">Статус задачи:</label>
            <?php $this->render('Partial/Select', ['form' => $this->form, 'name' => 'status']); ?>
        </div>
    <?php else: ?>
        <input type="hidden" name="status" value="0" />
    <?php endif; ?>

    <div class="mb-4">
        <label class="form-label">Введите имя:</label>
        <?php $this->render('Partial/Input', ['form' => $this->form, 'name' => 'name']); ?>
    </div>

    <div class="mb-4">
        <label class="form-label">Введите почту:</label>
        <?php $this->render('Partial/Input', ['form' => $this->form, 'name' => 'email']); ?>
    </div>

    <div class="mb-4">
        <label class="form-label">Введите описание:</label>
        <?php $this->render('Partial/Input', ['form' => $this->form, 'name' => 'content']); ?>
    </div>

    <button type="submit" class="btn btn-success">Сохранить</button>
</form>